### ISSUE TITLE
suggestion: when selecting a company, summarize the types of problems by frequency

### ISSUE THREAD

**Issue by iandouglas** [seanprashad/leetcode-patterns#102]
As a user, if I choose a company from the list, I'd like to see a quick summary at the top of the kinds of problems known to be asked by that company, by frequency.

For example, if I pick Amazon from the list, having something at the top that says:

`DFS: 26`, `DP: 18`, `Backtracking: 14`, `BFS: 14`, `Binary Search: 13`, `Heap: 13`
`Arrays: 12`, `2-pointer: 10`, `Fast & Slow Ptrs: 8`, `Trie: 8`
etc

This would help, for example, to narrow down which kinds of problems to study for a given company based on frequency. In this case, I should study DFS/Dynamic Programming/Backtracking/BFS way more than I should study bit manipulation, if I'm intervieiwng at Amazon.

**Comment by SeanPrashad** [comment]
Hey @iandouglas!! Thanks for suggesting this feature - it totally makes sense to me and would definitely be great to have!

**Comment by iandouglas** [comment]
Thanks @SeanPrashad . This site yo'uve put together is FANTASTIC. I've given it out to my students at turing.edu as well as people that I coach on interviewing.io. Keep up the great work!

**Comment by SeanPrashad** [comment]
That's incredible to hear @iandouglas!!!

This site started out as a side-project back in the final year of my undergrad - I was frustrated with finding free resources for software engineering interviews and could not afford premium subscriptions/courses, coming from a poor family. My hope for this website is to continue supporting individuals from all over the world in their own interview prep journey and I intended to make sure it stays free, open, and unbiased for as long as I own it!

**Comment by SeanPrashad** [comment]
That's incredible to hear @iandouglas!!!

This site started out as a side-project back in the final year of my undergrad - I was frustrated with finding free resources for software engineering interviews and could not afford premium subscriptions/courses (_as I come from a underprivileged family_).

My hope for this website is to continue supporting individuals from all over the world in their own interview prep journey and I intended to make sure it stays free, open, and unbiased for as long as I own it!

**Comment by seanprashad** [comment]
Hey @iandouglas - looping back with fantastic news! An awesome contributor, @hiromik, submitted a patch which adds a new header section showcasing the patterns when selecting a company:

![image](https://user-images.githubusercontent.com/13009507/131952659-32fa780a-59e4-43ba-8e8f-74d3f2aded05.png)

I'll consider this issue solved with #113, but feel free to open a new issue if any problems arise!

**Comment by iandouglas** [comment]
@hiromik this looks great, thanks for this!! Thanks @seanprashad for considering this idea, I think it'll be really useful for people to get an idea of things to study for a given company.
