### ISSUE TITLE
Add "Linked List" pattern to the problems

### ISSUE THREAD

**Issue by zerefwayne** [SeanPrashad/leetcode-patterns#106]

**Comment by SeanPrashad** [comment]
Hey @zerefwayne! Thanks for opening this issue! There are actually a handful of Linked List problems, however you'll find them under `In-place reversal of a Linked List` and `Fast and Slow pointers` problems. You could also try searching the webpage for `Linked`, which might be also helpful!

I don't think I'll move these two drop-down items to a single `Linked List` item as a `Linked List` isn't a pattern like `DFS`/`BFS` etc, but a data structure. Let me know if you have any other questions/suggestions!! 😁
