### ISSUE TITLE
Support for Dark mode

### ISSUE THREAD

**Issue by Shivam60** [seanprashad/leetcode-patterns#110]
As title says if site can have dark background it would be great.

**Comment by seanprashad** [comment]
@bharati-21 Feel free to give it a shot! I was tinkering before with Styled Components but never got around to making the changes here. Please let me know if you have any questions!

**Comment by Shashank5665** [comment]
Hello again @seanprashad !😁, is this still open? @bharati-21 did you complete this ?

**Comment by seanprashad** [comment]
Hey @Shashank5665! I think it's safe to consider this issue still open - feel free to take a crack at it. Note that it will be a little more difficult than your previous bug! Good luck!

**Comment by Shashank5665** [comment]
Sure @seanprashad, I will definitely take a look at it.

**Comment by LordChakshu** [comment]
Hey @seanprashad if this is open I would like to take it up!
Thanks.

**Comment by seanprashad** [comment]
Hey @LordChakshu - yes, feel free to pick this up. I should note that it is not as easy as it looks and will require a bit of work. Let me know if you have any questions - a lot of people would love to have this implemented!

**Comment by LordChakshu** [comment]
@seanprashad could you suggest few color codes for dark mode.
This is what I have currently come up with
![image](https://github.com/user-attachments/assets/8df86625-3f1f-4b75-b686-690ceb9a34e5)

**Comment by seanprashad** [comment]
@LordChakshu Nice work! I think we can take inspiration from different Design Systems used at larger tech companies:

1. [Atlassian - Picking colors for dark mode](https://atlassian.design/foundations/color-new/color-palette-new#picking-colors-for-dark-mode)
2. [Material Design - Dark theme](https://m2.material.io/design/color/dark-theme.html)

Feel free check out some of the colours from either of the above links - our main goal is to ensure readability for all content (_i.e. hyperlinks, headers, buttons etc_)!

**Comment by LordChakshu** [comment]
Hey @seanprashad Above resources were quiet helpful, I was able to implement dark mode 
I have attached snapshots.
Let me know If these are good to go.
Thanks
![image](https://github.com/user-attachments/assets/f929a3f6-77ae-4458-8b8b-437f57359cec)
![image](https://github.com/user-attachments/assets/f406b904-aa04-47ac-a687-44f6f38ba656)
![image](https://github.com/user-attachments/assets/c12c3637-e2af-455a-becb-d996631b0e26)
![image](https://github.com/user-attachments/assets/91e794a2-52cd-4226-b18c-a7def57e3f67)

**Comment by LordChakshu** [comment]
Hey @seanprashad I have raised PR for the same. Take a look at it whenever you get a chance.
Thanks.

**Comment by seanprashad** [comment]
Fixed with https://github.com/seanprashad/leetcode-patterns/pull/323
