### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by marquelamar** [seanprashad/leetcode-patterns#112]
Thank you for this. My copy of "Cracking the Code Interview" just arrived yesterday.

**Comment by seanprashad** [comment]
Great stuff @marquelamar! Remember that this is a journey with its ups and downs - my best advice to you would be to pace yourself with your learning and to take breaks every so often. Remember that looking at solutions is perfectly fine but try to seriously study them and fill in your weaknesses as you go!

Keep in touch!
