### ISSUE TITLE
Export as list to leetcode? 

### ISSUE THREAD

**Issue by ravikanthmp** [seanprashad/leetcode-patterns#123]
Could we have an option to export to leetcode as list ?

**Comment by ravikanthmp** [comment]
yes, the latter.  Idea is to enable 'clone' the list so that it shows up the 'Lists' dropdown

**Comment by Vikram-T** [comment]
I was able to create a list for most of the questions. It has a few extra questions which are from Blind 75 and doesn't have the premium questions: https://leetcode.com/list/9w0th9dj 

Missing premium questions:
https://leetcode.com/problems/word-squares
https://leetcode.com/problems/employee-free-time
https://leetcode.com/problems/design-search-autocomplete-system
https://leetcode.com/problems/meeting-rooms
https://leetcode.com/problems/alien-dictionary/
https://leetcode.com/problems/sequence-reconstruction
https://leetcode.com/problems/generalized-abbreviation
https://leetcode.com/problems/rearrange-string-k-distance-apart
https://leetcode.com/problems/index-pairs-of-a-string 

There are few extra questions. IDK where they came from.

**Comment by ravikanthmp** [comment]
Thank you Vikram!
