### ISSUE TITLE
Can we have a Progress Bar?

### ISSUE THREAD

**Issue by adityakrshnn** [seanprashad/leetcode-patterns#125]
Can we show a progress bar to highlight the completion of problems? It can motivate users to do more. We can also show individual progress bars along with an overall bar. We can even add celebratory confetti every time the progress moves. I can help you make this

**Comment by seanprashad** [comment]
Cool idea @adityakrshnn - feel free to open a PR and we can discuss things from there! Thank you!

**Comment by saqiurila** [comment]
@seanprashad I can take a stab at this if no one else is working on it.

**Comment by seanprashad** [comment]
Hey @saqiurila! Sure - feel free to ping me if you get stuck. I'n totally open to any design you come up with, as long as it accurately tracks the completed questions!

**Comment by saqiurila** [comment]
@seanprashad I don't know if there's a faster way of communication than replying back here, but below is what I have currently. Do you have any suggestions? (Yes, I "stole" the design from leetcode lol)

![image](https://user-images.githubusercontent.com/3427553/205474094-47e5bdcf-65fa-4001-a48e-07327648dfc8.png)

**Comment by seanprashad** [comment]
Wow! That looks like a solid start - would you be able to open a Pull Request so I could pull in the changes locally to see? We might want to shrink the "_progress circle_" a tiny bit, but it looks solid overall! Great work!
