### ISSUE TITLE
Add QuickSelect pattern category?

### ISSUE THREAD

**Issue by a5ehren** [seanprashad/leetcode-patterns#128]
Problems like "Kth Largest Element in an Array" that are currently tagged as "Heap" now have interviewers expecting you to use quickselect on them because it is faster in O() time. I noticed the site does not have a category for QS at the moment, but apparently this is starting to be expected?

**Comment by seanprashad** [comment]
Hey @a5ehren! You make a great point and I agree that we can introduce the `Quickselect` pattern, although I remember only coming across 1-2 well though-out questions that required it.

How do you feel about opening a PR? 😀
