### ISSUE TITLE
A column showing question number

### ISSUE THREAD

**Issue by RealArv** [seanprashad/leetcode-patterns#130]
Can you add a column which will show the question number with respect to that question? It will be much easier to navigate

**Comment by seanprashad** [comment]
Hey @RealArv! Thank you for this - I was wondering if you could clarify what you mean't by:

> show the question number with respect to that question

For example, https://leetcode.com/problems/contains-duplicate/ is Leetcode #217, so would you want to see a column showcasing `217`? The reason I'm asking is that we currently don't store this - [see here for what we do](https://github.com/seanprashad/leetcode-patterns/blob/712626c796df6cab5276756d4dd44366968f5369/src/data/index.js#L2-L10).

**Comment by RealArv** [comment]
Hey Sean! What I meant is to add a column which will show question numbers,
so that a person can remember where the particular question is . For
example the 4th question is 'single number'. If I wanted to get the 100th
question, I just have to look for that in that column instead of manually
remembering where it was. I can just note down the question numbers which I
couldn't solve and can come back to it later.
BTW Thanks for creating this list tho, its extremely helpful for a
person who just got into data structures and coding.

**Comment by seanprashad** [comment]
Thanks a bunch for that explanation! With #132 now landed in `master`, you'll be able to view the question ID when you hover over the checkbox:

![Question_ID_In_Tooltip](https://user-images.githubusercontent.com/13009507/143804939-3494f987-902c-448f-be6b-1f63366d617b.gif)

Best of luck in your studying and feel free to circle back if you have any other questions/comments! 😁
