### ISSUE TITLE
Add a confirmation for Reset button

### ISSUE THREAD

**Issue by ducalpha** [seanprashad/leetcode-patterns#133]
The current `Reset` button immediately clears all the progress (i.e., the check boxes) by only 1 click. It would be better to avoid accidental resetting the progress by adding a Reset Confirmation dialog.

**Comment by philiplee13** [comment]
Hi @seanprashad - was it okay for me to try to take this one on? Also was there a "level" of confirmation that you wanted for this?
ie. Did you just want a pop up - or did have something specific in mind?

Thanks!

**Comment by seanprashad** [comment]
Hey @philiplee13 👋🏽 Yeah for sure, please feel free to give it a shot! I was thinking of a simple modal window with a `Confirm` button in green and a `Cancel` button in grey, but feel free to get creative ✌🏽

**Comment by seanprashad** [comment]
Will be fixed with #163
