### ISSUE TITLE
Reusing the templete

### ISSUE THREAD

**Issue by kaleem68** [seanprashad/leetcode-patterns#136]
I find https://seanprashad.com/leetcode-patterns/ web interface super useful and productive, what is the best way so we can create independent list using this web interface. Only way I see is to clone repo and dump new questions data and redeploy independently! Can we do better?

**Comment by seanprashad** [comment]
Hey @kaleem68, thanks for reaching out! If you want to reuse the existing user interface, but with your own custom list, the best way would be to create a fork on GitHub, clone that fork your local machine, and then edit [`src/data/index.js`](https://github.com/seanprashad/leetcode-patterns/blob/master/src/data/index.js).

Please keep in mind that by doing so, you'll have to follow the rules of the [`LICENSE`](https://github.com/seanprashad/leetcode-patterns/blob/master/LICENSE.md) that I've selected for this repo!

Please let me know if you have any other questions! 😁

**Comment by seanprashad** [comment]
Considering this resolved! Please reach out if you have any other questions!
