### ISSUE TITLE
Can we have the list in doc or pdf format also?

### ISSUE THREAD

**Issue by Banashri** [seanprashad/leetcode-patterns#138]

**Comment by seanprashad** [comment]
Hey @Banashri, thank you for reaching out!! I'll open this up to any contributors - I don't personally plan on making the list available via a `.doc`/`.pdf` since it might get out of date, but feel free to try saving the webpage as a `PDF` and see how that turns out!

**Comment by Banashri** [comment]
@seanprashad Thanks. 

Just an idea:
The problems list (some data file, I suppose) that you use for the UI can be feed into the document /excel generation code, each time you update the UI.

**Comment by seanprashad** [comment]
Relates to #154
