### ISSUE TITLE
https://leetcode.com/problems/target-sum/ should be part of DP, not Backtracking

### ISSUE THREAD

**Issue by RishiPrakash** [SeanPrashad/leetcode-patterns#14]
https://leetcode.com/problems/target-sum/ is related to DP and DFS more and lesser to Backtracking.
Can we change it's tagging?

**Comment by SeanPrashad** [comment]
Hey @RishiPrakash! After taking a look at the solution to the question once, I think you're totally right that this question relates to DFS/DP more than Backtracking.

The 'brute force' heavily resembles DFS! I'll add it to `DFS` for patterns now and make note in #10 to add `DP` as a second pattern - thanks!
