### ISSUE TITLE
Can we have leetcode list of all of your questions (so that it's possible to directly solve there and the list auto updates for all solved questions).

### ISSUE THREAD

**Issue by mehul1011** [seanprashad/leetcode-patterns#151]

**Comment by seanprashad** [comment]
Hey @mehul1011! I _think_ you'd like something like https://leetcode.com/list/9w0th9dj/? (All credit goes to @Vikram-T in their post [here](https://github.com/seanprashad/leetcode-patterns/issues/123#issuecomment-981291804).

Please let me know if this is what you were looking for!

**Comment by seanprashad** [comment]
Hey @mehul1011! I _think_ you'd like something like https://leetcode.com/list/9w0th9dj/? (All credit goes to @Vikram-T in their post [here](https://github.com/seanprashad/leetcode-patterns/issues/123#issuecomment-981291804)).

Please let me know if this is what you were looking for!

**Comment by mehul1011** [comment]
That is it, thanks a lot!!
