### ISSUE TITLE
Request for open source license for this website

### ISSUE THREAD

**Issue by mm1705** [SeanPrashad/leetcode-patterns#16]
Hi @SeanPrashad, 
I would like to suggest using a license for this website. You may refer to [choosealicense.com](https://choosealicense.com/), a site maintained by GitHub, for picking a license. This website also explains how licenses work and describe some popular licenses in detail.

**Comment by SeanPrashad** [comment]
Great idea @mm1705 - I've added the [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/) as I want this project to stay open-source in its entirety and to disallow anyone from making a "closed" version for profit.
