### ISSUE TITLE
Edit to Tips section

### ISSUE THREAD

**Issue by mcwinters** [seanprashad/leetcode-patterns#173]
I believe you should add QuickSelect to the Tips portion under "If asked for top/least K items then". It is usually optimal and a better choice than heap, although more difficult.

**Comment by seanprashad** [comment]
Hey @mcwinters! You're totally right - would you like to open a PR for it? Here's what we need to change ([Direct file URL](https://github.com/seanprashad/leetcode-patterns/blob/master/src/components/Tips/index.js#L38)):

```diff
diff --git a/src/components/Tips/index.js b/src/components/Tips/index.js
index 54dbb50..6643605 100644
--- a/src/components/Tips/index.js
+++ b/src/components/Tips/index.js
@@ -36,6 +36,7 @@ If asked for maximum/minimum subarray/subset/options then

 If asked for top/least K items then
 - Heap
+- Quick Select

 If asked for common strings then
 - Map
 - ```
