### ISSUE TITLE
Retrieve companies using Leetcodes API

### ISSUE THREAD

**Issue by seanprashad** [seanprashad/leetcode-patterns#209]
In #179, we introduced functionality to automatically retrieve the difficulty of a question via Leetcode's GraphQL API. It would be great for us to extend this functionality to also retrieve and populate [questions.json](https://github.com/seanprashad/leetcode-patterns/blob/master/src/data/questions.json) with the information.

In order to grab the list of companies, we'll need to authenticate via the regular `/login` API endpoint, retrieve the session token, and pass that in the payload with the GraphQL queries. I might be wrong, but that's how I'm thinking we should tackle it - we can leverage other great repos like https://github.com/realvect0r/leetcode-api/blob/32b5658fd8e5c27ebddfe7f1198218e9e13be64e/src/lib/leetcode.ts#L35 if that makes more sense.

Also, I think there is where we'll need to add a username and password as secrets in GitHub so our Python script grab the username/password like SECRETS.USERNAME and SECRETS.PASSWORD. I've added `LEETCODE_USERNAME` and `LEETCODE_PASSWORD` as repository secrets that we can use them in our GitHub Workflow!

**Comment by leo-step** [comment]
I was looking into this and I ran into some difficulties with the login. It seems that LeetCode implemented reCaptcha and these previous methods of logging in don't work anymore. The [top issue](https://github.com/realvect0r/leetcode-api/issues/12) on the repo you linked describes this issue.

**Comment by seanprashad** [comment]
> I was looking into this and I ran into some difficulties with the login. It seems that LeetCode implemented reCaptcha and these previous methods of logging in don't work anymore. The [top issue](https://github.com/realvect0r/leetcode-api/issues/12) on the repo you linked describes this issue.

Ahh, thanks for surfacing that! It might still be a somewhat manual process where I'll have to login and grab my `LEETCODE_SESSION` then update a new secret, something like `LEETCODE_SESSION_TOKEN`.

**Comment by seanprashad** [comment]
Fixed with #210
