### ISSUE TITLE
Some questions lost their list of companies

### ISSUE THREAD

**Issue by leo-step** [seanprashad/leetcode-patterns#221]
e.g. Range Sum Query was previously tagged with Facebook and Adobe, but now doesn't have any companies. Can we check to make sure this is correct?

Edit: This is the complete list of these questions.

![Screen Shot 2022-08-07 at 1 54 31 PM](https://user-images.githubusercontent.com/44349262/183304488-4c846934-c6bd-4173-9955-3276fddc4e34.png)

**Comment by seanprashad** [comment]
Confirming that Range Sum Query has Facebook/Amazon still showing within 6 months:
![Screenshot 2022-08-07 at 2 31 25 PM](https://user-images.githubusercontent.com/13009507/183305815-739dfb10-b6d1-452d-8aba-6ea8e79fa661.jpg)

**Comment by seanprashad** [comment]
I'm wondering if we're getting rate-limited? 🤔 Going to try removing all but these problematic questions and run the script locally

**Comment by seanprashad** [comment]
Okay I figured it out - in the response, the `"1"`, `"2"`, or `"3"` represent the following tabs:

```
1 -> 0-6 months
2 -> 6 months - 1year
3 -> 1 year - 2 years
```

See below for [`Generalized Abbreviation`](https://leetcode.com/problems/generalized-abbreviation/):

```
'company_tag_stats': '{"3": [{"taggedByAdmin": false, "name": "Adobe", "slug": "adobe", "timesEncountered": 6}, {"taggedByAdmin": false, "name": "Google", "slug": "google", "timesEncountered": 4}, {"taggedByAdmin": true, "name": "Palantir Technologies", "slug": "palantir-technologies", "timesEncountered": 0}], "2": [{"taggedByAdmin": false, "name": "Facebook", "slug": "facebook", "timesEncountered": 5}, {"taggedByAdmin": false, "name": "Amazon", "slug": "amazon", "timesEncountered": 2}], "1": []}'
```

This makes sense why no companies appear for it, because it has not been asked within 0-6 months (_we currently only look for `"1"`_).

Does this make sense? I think we could also possible get the `"2"` and `"3"`, however those would be 6 months to a year, and beyond that. I like the idea of using `"1"` and `"2"` to represent "Companies that have asked this question in the past year".

What are your thoughts @leo-step?

**Comment by seanprashad** [comment]
Here's the code change if we want to pursue the 1 year scope:

```python
    # Retrieve companies who have asked this question within 0-6 months
    leetcode_companies_6mth = json.loads(
        response["data"]["question"]["company_tag_stats"])["1"]
    # Also retrieve companies who have asked this question within 6 months - 1 year
    leetcode_companies_1yr = json.loads(
        response["data"]["question"]["company_tag_stats"])["2"]
    leetcode_premium = response["data"]["question"]["is_paid_only"]

    companies = []

    for leetcode_company in leetcode_companies_6mth:
        company = {
            "name": leetcode_company["name"],
            "slug": leetcode_company["slug"],
            "frequency": leetcode_company["timesEncountered"]
        }

        companies.append(company)

    for leetcode_company in leetcode_companies_1yr:
        company = {
            "name": leetcode_company["name"],
            "slug": leetcode_company["slug"],
            "frequency": leetcode_company["timesEncountered"]
        }

        companies.append(company)

    sortedCompaniesByFreq = sorted(companies, key = lambda d: d['frequency'], reverse=True)
```
