### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by DimaAmega** [seanprashad/leetcode-patterns#242]
[web site](https://seanprashad.com/leetcode-patterns/) is down. It's because github pages down

**Comment by seanprashad** [comment]
Thanks for the heads up @DimaAmega - I'm not sure if GitHub pages itself is down (_https://www.githubstatus.com/ shows everything fine as of Oct 18/22 at 8:36am ET_), but I noticed that GitHub pages was somehow disabled for my main website, which will be a problem.

I've re-enabled it and I'm currently re-deploying `leetcode-patterns` to see if that will resolve things.

**Comment by fdemir** [comment]
Thanks. It's running. @seanprashad

**Comment by seanprashad** [comment]
**Update:** The deployment was successful and the website should be up and running now!

**Comment by DimaAmega** [comment]
Yep, thank you for fast reaction!

**Comment by seanprashad** [comment]
Closing as website has been back up for a few hours now!
