### ISSUE TITLE
Switching order of reverse linkedlist and palindrome linkedlist?

### ISSUE THREAD

**Issue by ap247** [seanprashad/leetcode-patterns#243]
Would you consider switching the order of reverse LinkedList and palindrome linked list since palindrome seems to require reverse in its solution, making reverse a natural lead into palindrome?

**Comment by seanprashad** [comment]
Hey @ap247! Thanks for the suggestions - I've gone ahead and moved `Reverse a Linked List` in front of `Palindrome Linked List`. Thank you!

**Comment by ap247** [comment]
Hey Sean, thanks for the quick change! I really appreciate the list and that you're still actively maintaining it.
