### ISSUE TITLE
how do i get started using this repository on my local machine?

### ISSUE THREAD

**Issue by theefreelancer** [seanprashad/leetcode-patterns#267]
Thanks to the team, for making this knowledge accessible to everyone!
I was wondering about the steps on how can i get started with using this very repository, in a way that I can solve problems following the patterns highlighted.
And if I am to utilize this very repository on my local machine which directory has the files for this knowledge or patterns?
I suppose this could assist someone in the future who may also want to onboard and use this knowledge.

**Comment by seanprashad** [comment]
Hey @theefreelancer! Thanks for checking out this repo!

You actually don't need to clone the repo to "_get started_" - the website that is generated from this repo can be found here: https://seanprashad.com/leetcode-patterns/.

As far as utilizing this repository - it's different for everyone. Some individuals like to target `Easy` questions, or all `Easy` questions under a specific pattern before moving onto the respective `Medium` ones. Again, it's all preference, but the point is that you shouldn't rush through them, but solve (_and study_) at your own pace. The last thing you want to do is memorize a question, then be asked it in an interview and completely mess it up - that would totally suck!

Good luck in your studies!
