### ISSUE TITLE
Project set up instructions

### ISSUE THREAD

**Issue by Dheeraj6778** [seanprashad/leetcode-patterns#268]
Can anyone document the project set-up instructions so that it will help beginners like me to set the project up on local machine.

**Comment by seanprashad** [comment]
👋🏽 This is something I can help with but for now, you can:

1. Clone this repository to your local machine: https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository
2. Ensure your version of Node.js is `v14.17.3`
3. Run `npm install` from within the root directory of this project
4. Run `npm start` to build and locally launch the website, available at http://localhost:3000/leetcode-patterns

**Comment by Dheeraj6778** [comment]
Thanks! It's working now
