### ISSUE TITLE
Design Gurus & original author acknowledgements

### ISSUE THREAD

**Issue by smith558** [seanprashad/leetcode-patterns#270]
The **Design Gurus**, the team behind the original grokking the coding interview course as well as behind the Educative platform grokking the coding interview course, is missing in the acknowledgements list.

the own course:
https://www.designgurus.io/course/grokking-the-coding-interview

The first blog post of the original author (of the actual patterns list) with the design patterns first unveiled:
https://emre.me/categories/#coding-patterns

**Comment by seanprashad** [comment]
Fantastic, thank you very much for bringing this to my attention @smith558 - will update it shortly!
