### ISSUE TITLE
"Sliding Window" missing problems

### ISSUE THREAD

**Issue by smith558** [seanprashad/leetcode-patterns#276]
- [ ] https://leetcode.com/problems/maximum-average-subarray-i/
- [ ] https://leetcode.com/problems/maximum-number-of-vowels-in-a-substring-of-given-length/
- [ ] https://leetcode.com/problems/max-consecutive-ones-iii/
- [ ] https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/

**Comment by seanprashad** [comment]
You should consider contributing if you have the chance! See this PR for how I've added a new question: https://github.com/seanprashad/leetcode-patterns/pull/275

Don't worry about the `companies` section - that is something that is populated by a cron job that we can manually run after the questions have been added.

**Comment by smith558** [comment]
> You should consider contributing if you have the chance! See this PR for how I've added a new question: #275
> 
> Don't worry about the `companies` section - that is something that is populated by a cron job that we can manually run after the questions have been added.

Happy to do that, my contribution timeline is a bit longer right now so might take a week or two. I opened the issues mostly for tracking purposes, I may add more problems as I encounter them and whoever manages to open PRs for them at various times can tick them off here.
