### ISSUE TITLE
There are two same type of dropDown items in dropDown 

### ISSUE THREAD

**Issue by aman246149** [seanprashad/leetcode-patterns#279]
![image](https://github.com/seanprashad/leetcode-patterns/assets/53884276/7aeaac6d-1cc3-4d60-a479-ad5bdb856e58)

Please refer to this screenshot
There are two identical types of dropDown items in dropDown 
1-Array
2-Arrays

Is it a bug or if not what's the difference between them

**Comment by seanprashad** [comment]
Thanks a ton for raising this bug @aman246149 - I've fixed it such that all questions should be labelled with `Arrays` and not `Array`!
