### ISSUE TITLE
Tips page UI improvement

### ISSUE THREAD

**Issue by surjendu104** [seanprashad/leetcode-patterns#289]
Hey @seanprashad  The Tips page needs styling> If you allow I am ready to work on this. Also tell your preferred styling if you have any

**Comment by seanprashad** [comment]
Hi @surjendu104 - I chose to leave the page without styling so others could copy and paste the contents directly into their own notes. If we want to adjust how things look in the future, I'll open up a new issue for others to help out with. Thank you!
