### ISSUE TITLE
Option to see patterns

### ISSUE THREAD

**Issue by bhavesh-banknovo** [SeanPrashad/leetcode-patterns#31]
Hey Sean, thank you for the list, it has been really helpful. I was wondering whether it would be possible to add a switch or something at the top to toggle on/off the pattern types for each question. Currently all the pattern types are hidden unless a user clicks check at the left. While hiding the pattern type is definitely useful, I imagine that there are quite a few people who may be trying to find questions for a certain pattern type. Hence the ability to toggle on/off the pattern types would be really useful. Thanks in advance!

**Comment by SeanPrashad** [comment]
Hey @bhavesh-banknovo 😁 I'm super happy to hear that you've found value from the list!

I totally agree with you that having a slider toggle of some sort to show/hide patterns at will is a fantastic idea. I'm going to look into this over the weekend and try to get some progress made on it. I am working full-time now so I'm usually jam packed during the weekdays but I know I should have implemented this sooner.

In the meantime, you can filter by pattern via the drop down list at under the `Pattern` category:

<img width="269" alt="Screen Shot 2020-06-25 at 9 14 29 PM" src="https://user-images.githubusercontent.com/13009507/85810391-e19da000-b728-11ea-944c-89b07f8cc70f.png">

**Comment by SeanPrashad** [comment]
Related: https://github.com/SeanPrashad/leetcode-patterns/pull/28

**Comment by SeanPrashad** [comment]
Hey @bhavesh-banknovo! I'm happy to say that this has been implemented and you'll now see a toggle beside the Pattern column header:

![image](https://user-images.githubusercontent.com/13009507/85929862-183cfd00-b886-11ea-9252-f65f68dfcaad.png)

Clicking on this (or the label `Show/Hide Patterns`) will now toggle all patterns between being hidden or being shown!

Please let me know if you find bugs of any sort ✌🏽
