### ISSUE TITLE
Questions not working in production

### ISSUE THREAD

**Issue by alysonramos** [seanprashad/leetcode-patterns#312]
Hello, i started using the website, but seems it stopped to work
![image](https://github.com/seanprashad/leetcode-patterns/assets/124684823/d1873981-3df3-4f4d-9633-3cc0b8bcfce5)

**Comment by seanprashad** [comment]
Hi @alysonramos! By "_stopped to work_", can you describe what stopped working? Does this mean that scrolling doesn't work, or filtering by a certain company?

**Comment by alysonramos** [comment]
@seanprashad mine it is only showing the past questions I did, i mean I only did 4, and it is only showing 4
![image](https://github.com/seanprashad/leetcode-patterns/assets/124684823/f0b3977f-16e1-434b-adf6-07ced57951ea)

**Comment by seanprashad** [comment]
@alysonramos Understood - could you try toggling the completed questions and see if that resolve things:

![ToggleCompletedQuestions](https://github.com/seanprashad/leetcode-patterns/assets/13009507/b4c48406-61df-4427-a6a7-5ae7f0d6550e)


Also, if you have steps to reproduce, that would be great!

**Comment by seanprashad** [comment]
Np! Happy studying!
