### ISSUE TITLE
Issue in display of count of medium problems 

### ISSUE THREAD

**Issue by adityajain60** [seanprashad/leetcode-patterns#318]
Hello Sean,

First of all thanks alot for making such a comprehensive list. It has helped me alot through my preperation.

I wanted to point out an error in the display of number of medium problems solved in the website, due to which the count of total problems solved is also getting bugged. I would like if you could fix this issue, as this seems like a minor thing. It would help me alot to know that status of completetion of the list, as it not only motivates me but also helps to keep track of questions solved. 

Thank you
![Screenshot 2024-07-12 175641](https://github.com/user-attachments/assets/74038edc-9a87-4360-8dcd-c09604eb8462)

**Comment by seanprashad** [comment]
👋🏽 Thanks for reaching out! I can confirm that I also see this - I'll try to check out what recent change broke it and let you know once a fix has been deployed. Thank you!

**Comment by seanprashad** [comment]
This should be fixed now - could you please refresh the website if you have it open and let me know?

**Comment by adityajain60** [comment]
I have checked and it is working now.
Thanks alot for the immediate response and help.
