### ISSUE TITLE
Does not work if adblocker is turned on

### ISSUE THREAD

**Issue by bigfoot31** [seanprashad/leetcode-patterns#327]

**Comment by seanprashad** [comment]
Hi @bigfoot31! Which browser and adblocker are you using? Can you expand on what "Does not work" mean?

**Comment by bigfoot31** [comment]
I fixed it. It wasn't adblocker related. 
What fixed it for was clearing the localstorage. I suspect the old key-value value in localstorage is incompatible with the newer version of the website. I had opened the website after 6 months.
