### ISSUE TITLE
Add Questions for Stacks and Queues 

### ISSUE THREAD

**Issue by rajatsing** [SeanPrashad/leetcode-patterns#38]

**Comment by SeanPrashad** [comment]
Thanks for opening this issue @rajatsingh25aug!

I'd be more than happy to accept pull requests that add on stack/queue questions you feel are great to study. New questions would be added after [question 171](https://github.com/SeanPrashad/leetcode-patterns/blob/8ebdb87d04726cbd0b92fdfd21416540b0bd8b30/src/data/index.js#L2048).

I'd be able to help supply the companies for each respective question once a PR is up!

**Comment by rajatsingh25aug** [comment]
@SeanPrashad are you planning to add more questions in general, like increasing the number of questions?.

**Comment by SeanPrashad** [comment]
I feel the list covers a handful of patterns at this moment, but I'm always open to figuring out if there are patterns we're missing, or new questions that fit into the existing categories.

I know existing questions, like [Validate Parentheses](https://leetcode.com/problems/valid-parentheses/) and common [Min Stack](https://leetcode.com/problems/min-stack/) would fall under the `Stack` category as their solutions use a Stack, and existing patterns like `Sliding Window` and `BFS` usually use a `Queue` data structure for the optimal solution.

Feel free to gather a list, open a PR and I'd be more than happy to help mentor you or anyone else!

**Comment by rajatsingh25aug** [comment]
thanks sean, will keep this in mind.

**Comment by Sai-Adarsh** [comment]
+1, and you're doing a great job @SeanPrashad

**Comment by SeanPrashad** [comment]
Closing this as I'd like to have separate GitHub issues opened for when individuals submit certain questions to add! Thanks everyone! ✌🏽
