### ISSUE TITLE
Show Breakdown of Questions Completed By Difficulty

### ISSUE THREAD

**Issue by SeanPrashad** [SeanPrashad/leetcode-patterns#39]
> If it is possible can you add some kind of tables where we can see how many easy/medium/hard questions we already done on the top of the page

**Comment by SeanPrashad** [comment]
@rishav142k opened #47, which is related to this!

```
So, there is a total number of questions present there, but I think it would be beneficial if we could also see the number of questions we have done, including the number of easy medium and hard questions number in the list. I think it would be pretty useful feature. Also, if it is approved, I would like to work upon it, too.
```

**Comment by SeanPrashad** [comment]
I'd love to have you give this a shot @rishav142k!

The code for generating the table is found [here](https://github.com/SeanPrashad/leetcode-patterns/blob/master/src/components/Table/index.js).

Here's what I was thinking on how we could solve this problem:

- For each row, ie. each question, there is a custom `checked` column that is added here: https://github.com/SeanPrashad/leetcode-patterns/blob/781b75825cfbc213f7e5a83a9f6f26b9fb9fa071/src/components/Table/index.js#L73-L89

- Step 1 might be to do it the brute force way and keep a counter of every question that is checked

- Step 2 could then add some logic to extract the respective difficulty for the row, ie. question, found here: https://github.com/SeanPrashad/leetcode-patterns/blob/781b75825cfbc213f7e5a83a9f6f26b9fb9fa071/src/components/Table/index.js#L175-L189

- Step 3 would then be to group all of those under `Easy`, `Medium`, and `Hard` and print those out in the dev console

- Step 4 could possibly add a small section at the top that displays how many `Easy`, `Medium`, and `Hard` questions a user has done

What do you think about this approach? The scope of this problem is bigger than you might think but I'd be more than happy to help mentor and work together to help land this feature! 😁

**Comment by rishav142k** [comment]
I'll try and give it a shot. Yeah, this is definitely a lot more than I expected. I'll reach out to you if I need any help and mentoring. By the way, this is a really cool project. I'd love to help here.

**Comment by SeanPrashad** [comment]
Hey @rishav142k! Just wanted to pop by and see if you're stuck at all - happy to help answer any and all questions!

**Comment by rishav142k** [comment]
Hi! I have been kinda busy these days.(Online classes, I tell you). Will start this in this week, and will let you know the problems I would be facing.

**Comment by juhitiwari** [comment]
Hello @SeanPrashad. I have tried to give this feature a shot. Could you please review it in the PR and suggest any improvements/further work?

**Comment by SeanPrashad** [comment]
Thanks so much @juhitiwari!!! I've made a note to give it a look this weekend when I have more free time 😁

**Comment by SeanPrashad** [comment]
This is now complete! 🎉 Thanks again for helping land this @juhitiwari!!! 😁

**Comment by juhitiwari** [comment]
Thank you!
