### ISSUE TITLE
One More Tip to consider

### ISSUE THREAD

**Issue by Manideep2207** [SeanPrashad/leetcode-patterns#42]
If the problem is to be solved inplace, we will get to the solution either by
1. swapping the corressponding values.
2. Storing one or more different values in the same pointer

**Comment by SeanPrashad** [comment]
Hey @Manideep2207! Thank you for this tip!

Would you be able to link a question that this tip applies to? I think I have an idea about what you're referring to but I'd like to be 100% sure 😀

**Comment by Manideep2207** [comment]
Thanks for getting back to me so quickly.
I will attach those relevant problems in github.

**Comment by Manideep2207** [comment]
<a href = "https://leetcode.com/problems/first-missing-positive/">41. First Missing Positive</a>
Sort an array of 0s, 1s and 2s
<a href = "https://leetcode.com/problems/set-matrix-zeroes/">73. Set Matrix Zeroes</a>
<a href = "https://leetcode.com/problems/rotate-image/">48. Rotate Image</a>
Block swap algorithm(<a href = "https://www.geeksforgeeks.org/block-swap-algorithm-for-array-rotation/?ref=rp">GFG</a>)

<strong>For the case-2:</strong>
Done the problem where I have to store two values in the same pointer(will get those two by quotient and remainder by dividing the value of pointer with certain value). For now, I couldn't find this type of problem.

<strong>But I will definitely add more to the list in future.</strong>

**Comment by SeanPrashad** [comment]
Hi @Manideep2207! I haven't forgotten about adding these - I just haven't had time to check them out on my own in the past few weeks. I plan to look them over soon 😃

**Comment by SeanPrashad** [comment]
A month later and I've finally gotten around to adding this tip! Thanks again for suggesting it @Manideep2207, myself and others definitely appreciate it 😁

**Comment by Manideep2207** [comment]
Thanks so much for considering this @SeanPrashad
