### ISSUE TITLE
Question Listed Twice

### ISSUE THREAD

**Issue by orbit-stabilizer** [SeanPrashad/leetcode-patterns#44]
Remove Duplicates from Sorted List is listed twice.

**Comment by SeanPrashad** [comment]
Thanks for the heads up @orbit-stabilizer!

Note that the two references are below:

https://github.com/SeanPrashad/leetcode-patterns/blob/4e5285246793368461d8403fbe76041d32c5768d/src/data/index.js#L685

and

https://github.com/SeanPrashad/leetcode-patterns/blob/4e5285246793368461d8403fbe76041d32c5768d/src/data/index.js#L1829

**Comment by SeanPrashad** [comment]
Fixed in https://github.com/SeanPrashad/leetcode-patterns/commit/a397147353f759d424b094ad153b7de1fe0f87b4
