### ISSUE TITLE
Binary Search Problem Add Pattern:  Allocate Books/painter partition and Sorted Array Median

### ISSUE THREAD

**Issue by aggarwalsachin** [SeanPrashad/leetcode-patterns#45]
Hi Sean Prasad ,the list you have provided is quite great I will suggest u to add these 2 problem in binary search as these are very popular interview problem quite known by name .I will update you if i will face any other good problem.These two problem are unique .

**Comment by SeanPrashad** [comment]
Hi @aggarwalsachin! I'm super happy to hear the list has been helpful to you 😁 

I didn't see the names of the problems you wanted to add - would you be able to tell me which # they are on Leetcode so I can add them right away? Thank you!!

**Comment by SeanPrashad** [comment]
Just wanna touch base to see if you had some time to help me find the 2 problems on leetcode @aggarwalsachin - thanks!

**Comment by SeanPrashad** [comment]
"_Allocate Books_" = Unknown Question
"_Painter Partition_" = Unknown Question
"_Sorted Array Median_" = https://leetcode.com/problems/median-of-two-sorted-arrays/

**Comment by SeanPrashad** [comment]
Hey @aggarwalsachin, would you be able to verify if I found the right questions? Please see above - thank you!!

**Comment by aggarwalsachin** [comment]
Sorted array median link is fine for allocate books and painter partition
question refer the interviewbit  binary search section.

**Comment by aaryapatel007** [comment]
Here are the links:
https://www.interviewbit.com/problems/allocate-books/
https://leetcode.com/problems/median-of-two-sorted-arrays/
https://www.interviewbit.com/problems/painters-partition-problem/

**Comment by aaryapatel007** [comment]
https://leetcode.com/problems/majority-element/
add this too @SeanPrashad .
When will u add the problems in the previous comment?
Thanks

**Comment by SeanPrashad** [comment]
Hey @aaryapatel007 - thanks for pinging me. I'm super busy right now but I do plan on adding them - what do you think about submitting a pull request? I'd be more than happy to show you around!

**Comment by SeanPrashad** [comment]
Hey everyone - thanks for taking the time to let me know about new questions. I've gone ahead and added `Median of Two Sorted Arrays` and `Majority Element` to the existing list!

I've decided not to include the questions from _interviewbit.com_ as this repository is solely focused on questions from Leetcode. In the future, I'd definitely be open to including questions from other websites, but keeping questions based from Leetcode allows me to use my Premium subscription to constantly update which companies ask the respective questions!
