### ISSUE TITLE
Let the user see how many problems has he done

### ISSUE THREAD

**Issue by rishav142k** [SeanPrashad/leetcode-patterns#47]
So, there is a total number of questions present there, but I think it would be beneficial if we could also see the number of questions we have done, including the number of easy medium and hard questions number in the list. I think it would be pretty useful feature. Also, if it is approved, I would like to work upon it, too.

**Comment by rishav142k** [comment]
I see the issue has already been opened. Closing this now.

**Comment by SeanPrashad** [comment]
Thanks for opening this @rishav142k! I'd love to get this feature done as it has been requested a handful of times, but finding spare time isn't very easy. I'd love for you to give it a shot and I would be more than happy to help out where possible - see my comment [here](https://github.com/SeanPrashad/leetcode-patterns/issues/39#issuecomment-689010843) for more details!
