### ISSUE TITLE
Where's the subset pattern?

### ISSUE THREAD

**Issue by pendawleabhay** [SeanPrashad/leetcode-patterns#5]
I dont see the subset pattern

**Comment by SeanPrashad** [comment]
Questions that are about generating all subsets/permutations/combinations are found under the `Backtracking` pattern!

See below:

![image](https://user-images.githubusercontent.com/13009507/78318824-c1987f00-7533-11ea-97a7-b81a259ef25c.png)

**Comment by pendawleabhay** [comment]
ohh thanks
