### ISSUE TITLE
Hook up the solutions on each problem 

### ISSUE THREAD

**Issue by Aariv** [SeanPrashad/leetcode-patterns#57]
Need another column to point out the solution, in case if anyone wants to have a look at it. It could be visible based on the preferences.

**Comment by SeanPrashad** [comment]
Hey @Aariv! Thanks for the suggestion! This thought did cross my mind before but do you think I should link to the Leetcode Discuss section or the `solutions` branch for this repo? The vast majority of the solutions that I studied are optimal but I know that for some, I chose the easier way that made more sense to me.

Let me know what your thoughts are!

**Comment by SeanPrashad** [comment]
Hey @Aariv! I've added a `Solutions` column which now links to the relevant LeetCode Discuss section for the respective problem:

![image](https://user-images.githubusercontent.com/13009507/103159859-6f238080-479c-11eb-92a7-223c270448c6.png)

If you have any other suggestions/ideas, please let me know! ✌🏽
