### ISSUE TITLE
Ability to hide solved problems

### ISSUE THREAD

**Issue by snehasishroy** [SeanPrashad/leetcode-patterns#58]
Hi,

First of all wanted to say thank you for collating different patterns of problems.  Very helpful.

Now I would really love an ability to hide solved problems, or at-least show a count to user to how many problems he has already solved and how many are remaining.

Thank you.

**Comment by SeanPrashad** [comment]
Hey @snehasishroy - thanks a bunch of requesting this feature! #67 introduced the code to show just how many questions a user has completed for each level of difficulty.

I've gone ahead and added a total count to show how many questions a user has completed out of ALL of them:

![image](https://user-images.githubusercontent.com/13009507/103143506-60c65d80-46e5-11eb-8f38-c80ba24e78ed.png)

Please let me know if this works as intended and if you run into any troubles! Happy holidays!! 🎅🏽
