### ISSUE TITLE
Feature Request - Qns solved / Total qns

### ISSUE THREAD

**Issue by Sai-Adarsh** [SeanPrashad/leetcode-patterns#59]
Would be great to keep track of questions solved / total number of questions. Thanks.

Also, checkout: [Striver's list](https://docs.google.com/document/d/1SM92efk8oDl8nyVw8NHPnbGexTS9W-1gmTEYfEurLWQ/preview?pru=AAABdCnqg2E*ahqUNNC41Gk7UPJwB-AX6g) if you're adding more problems to the list.

**Comment by snehasishroy** [comment]
Hey, I raised a similar request hours ago 😄 
https://github.com/SeanPrashad/leetcode-patterns/issues/58

**Comment by SeanPrashad** [comment]
Thanks for that list as well as your suggestion @Sai-Adarsh - I'll try to get started on this towards the end of the year when I get some free time from regular work!

**Comment by SeanPrashad** [comment]
Hey peeps - great news! This feature has been landed in #67 - check it out on the live website or see below for a screenshot of what it looks like:

![image](https://user-images.githubusercontent.com/13009507/103143519-c286c780-46e5-11eb-8194-7bc2776bed51.png)
