### ISSUE TITLE
Pattern as a dropdown

### ISSUE THREAD

**Issue by pendawleabhay** [SeanPrashad/leetcode-patterns#6]
Would it make more sense if pattern was a drop down?

**Comment by SeanPrashad** [comment]
That's a fantastic idea!

I'm pretty sure I've seen something in `react-table` which can sort by a dropdown list based on all of the values - let me look into it in the next few days!

**Comment by SeanPrashad** [comment]
Hey @pendawleabhay - I just wanted to let you know that I was able to get this implemented as you asked!

If you do a "hard refresh" (<kbd>Shift</kbd> + <kbd>Cmd</kbd> + <kbd>R</kbd> on Mac for example), you should see the new drop down list for `Pattern`:

![image](https://user-images.githubusercontent.com/13009507/79488030-1c77af00-7fe7-11ea-9dbb-824170d09895.png)


I've also switched over the `Difficulty` filtering to use the new DDL as well:

![image](https://user-images.githubusercontent.com/13009507/79488084-31544280-7fe7-11ea-9897-8cdfd2b703f5.png)

If there's anything broken with the new functionality, please don't hesitate to open a new issue! Cheers 🙆🏽‍♂️

**Comment by pendawleabhay** [comment]
Awesome!
Thanks.
