### ISSUE TITLE
Two different sets of questions on different devices?

### ISSUE THREAD

**Issue by agauniyal** [SeanPrashad/leetcode-patterns#60]
Why do I see two different sets of questions on different devices. One of my device shows questions like arrays and stuff early on while my laptop and pc both show questions in this order -
```

  |   | Contains Duplicate | https://leetcode.com/problems/contains-duplicate/ | Arrays | Easy |  
  |   | Missing Number | https://leetcode.com/problems/missing-number/ | ArraysBit Manipulation | Easy |  
  |   | Find All Numbers Disappeared in an Array | https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/ | Arrays | Easy |  
  |   | Single Number | https://leetcode.com/problems/single-number/ | ArraysBit Manipulation | Easy |  
  |   | Climbing Stairs | https://leetcode.com/problems/climbing-stairs/ | Dynamic Programming | Easy |  
  |   | House Robber | https://leetcode.com/problems/house-robber/ | Dynamic Programming | Easy |  
  |   | Best Time to Buy and Sell Stock | https://leetcode.com/problems/best-time-to-buy-and-sell-stock/
```
DP question starts just at number 5 in this set.

**Comment by SeanPrashad** [comment]
Hey @agauniyal - off the top of my head, I'm not 100% sure. The order that is showing up on your laptop and PC looks correct to me! For reference, I've decided to sort questions **by their Difficulty** ([see the code here](https://github.com/SeanPrashad/leetcode-patterns/blob/838a153ac34e4f8b019fd9734cfbc3081bffa4c2/src/data/index.js#L2051)). The actual question list should not change very often and should be the same for both your laptop and other devices.

I'd try clearing the cache or doing a hard refresh and also try seeing if the problem persists across different browsers on the same device!

**Comment by SeanPrashad** [comment]
Closing as no follow-up from OP
