### ISSUE TITLE
Total question count is showing just easy questions count

### ISSUE THREAD

**Issue by juhitiwari** [SeanPrashad/leetcode-patterns#69]
![Screenshot from 2020-12-26 20-02-57](https://user-images.githubusercontent.com/26180236/103153279-7440f980-47b5-11eb-9a7e-ddf62940c8a5.png)
The total question count is just showing the number of easy questions count.

**Comment by SeanPrashad** [comment]
Ahh good catch! It's a small fix that I'll update once I get to my computer later today.

Thanks for the heads up @juhitiwari!!

**Comment by SeanPrashad** [comment]
This has been fixed! Please refresh the website when you get a chance - thanks!!
