### ISSUE TITLE
Update/Add Patterns

### ISSUE THREAD

**Issue by SeanPrashad** [SeanPrashad/leetcode-patterns#7]
As I'm continuing my own studies, I realized that there are some missing categories that would be very helpful, such as:

- ~`Design`~
- ~`Trie`~
- `Greedy`

When adding these new patterns, we should update the existing questions and their respective pattern, if need be, in [`src/data/index.js`](https://github.com/SeanPrashad/leetcode-patterns/blob/master/src/data/index.js).

**Comment by mm1705** [comment]
Should I just mention the questions of `Trie` category here or create a pull request editing [`src/data/index.js`](https://github.com/SeanPrashad/leetcode-patterns/blob/master/src/data/index.js)? <br />
If you'd prefer, I can share a leetcode list containing Trie questions which I find helpful in brushing up on Trie.

**Comment by SeanPrashad** [comment]
@mm1705 How do you feel about opening a PR? I'd be more than happy to work with you to get a patch merged and could definitely add the companies from LC premium where necessary.

Open a new issue and be sure to mention this one so we have a reference point for the future!

**Comment by mm1705** [comment]
@SeanPrashad I opened a PR, check it out. <br />
Also, I see that currently there is only one pattern per LC problem, I would suggest we change it to an array and support multiple patterns per problem.

**Comment by SeanPrashad** [comment]
I'm going to take a look at your PR @mm1705! Thank you for your work 🙆🏽‍♂️

**Comment by SeanPrashad** [comment]
Closing this as we've added the ability to have multiple patterns for each question.
