### ISSUE TITLE
Insert Interval is a medium question in LeetCode but its tagged as a hard question on your website.

### ISSUE THREAD

**Issue by jye48** [SeanPrashad/leetcode-patterns#73]
Hi Sean, thanks for making this site and keeping it up to date. I've been going through the problems and I found that the Insert Interval question is a medium question in LeetCode, but its tagged as a hard question on your website.

**Comment by SeanPrashad** [comment]
Hey Jerry!! Great catch - overtime it looks like Leetcode is updating the difficulty on some questions and you found one of them. I'll go ahead and make that quick change - stay tuned!

**Comment by SeanPrashad** [comment]
Okay this should be fixed now - it was just a tiny fix ([see here](https://github.com/SeanPrashad/leetcode-patterns/pull/74/files)). If you ever find a question that needs updating, feel free to ping me once again or even take a shot via a pull request - I'm always happy to help mentor!

Good luck studying and happy holidays!

P.S. I updated the companies for each question earlier this afternoon FYI 😬
