### ISSUE TITLE
Add "Last Solved On" Column

### ISSUE THREAD

**Issue by seanprashad** [seanprashad/leetcode-patterns#89]
It'd be nice to have a column that would show you when you last solved the question! This could be useful for individuals who want to re-attempt previous questions that gave them trouble (_like Backtracking for me_)

**Comment by LordChakshu** [comment]
Hey @seanprashad This would surely be an useful feature, I would like to take it up.

**Comment by seanprashad** [comment]
Hi @LordChakshu - please give it a shot! I think we can maybe save an array of dates, similar to how we do it for completed questions, and then show a tooltip whenever a user hovers over the checked completed box for the respective row.

Let me know if you'd like a hand with anything!

**Comment by LordChakshu** [comment]
Hey @seanprashad - I have come up with a Last Solved On Column that will display the date when user checks the box to mark question as completed(Unchecking box/ Reset will remove the date).
This way one can keep check on when they last solved the issue.
![Screenshot 2024-08-16 061322](https://github.com/user-attachments/assets/467d79a7-a871-48b9-956d-d9dcd9780580)

**Comment by seanprashad** [comment]
Nice work! Please feel free to open a pull request and I'll take a look when I get a chance. Thank you!

**Comment by LordChakshu** [comment]
Hey @seanprashad I have Raised the PR take a look when you get a chance.
Thanks.

**Comment by seanprashad** [comment]
Thank you! I'll get a chance to review it within the next week or so

**Comment by seanprashad** [comment]
Fixed with https://github.com/seanprashad/leetcode-patterns/pull/320
