### ISSUE TITLE
suggestion - add Frequency of question asked

### ISSUE THREAD

**Issue by NirmalSilwal** [SeanPrashad/leetcode-patterns#99]
Hi @SeanPrashad, it would be great to filter question by frequency. This would be helpful to those people who are interviewing soon. What do you think about this?

**Comment by SeanPrashad** [comment]
Hey @NirmalSilwal!! Thanks for the suggestion - by "_filter question by frequency_", do you mean to sort questions based on how "_popular_" they are? I'm not sure our [current data set](https://github.com/SeanPrashad/leetcode-patterns/blob/master/src/data/index.js) supports that and I'd have to take a best guess on how to implement it.

I think that one way could be to sort questions based on the number of companies that ask it but this changes all the time so it wouldn't be accurate!

**Comment by NirmalSilwal** [comment]
Hi @SeanPrashad to filter by frequency I mean to sort question based on how many companies have asked them. Let's say one question X is asked in 8 companies and another question Y in 5 companies. Then we can add that feature to sort by frequency where X occur first and Y after that.

For your better reference this is the similar concept used in **Leetcode frequency**.

I agree that those frequency changes all the times but  as per [this reference](https://github.com/SeanPrashad/leetcode-patterns#question-list) this is already not up-to date. So for whatever the list is there we can sort them by frequency.

**Comment by SeanPrashad** [comment]
Gotcha @NirmalSilwal!

**Comment by SeanPrashad** [comment]
Hey @NirmalSilwal - I wanted to let you know that this functionality was added in #104 by our friend @hiromik!

You can simply left-click on the `Companies` header to sort the questions based on the # of companies that have asked it recently:

https://user-images.githubusercontent.com/13009507/120931716-cff6a380-c6c0-11eb-8728-60ade2f28a85.mp4

I'll consider this issue solved but please let me know if anything else pops up! Thank you!

**Comment by KashyapCKotak** [comment]
Can't find this option now...

**Comment by seanprashad** [comment]
> Can't find this option now...

Hey @KashyapCKotak! This feature is working for me - would you be able to refresh your page and let us know if the issue still persists? It might be a bug we haven't discovered as yet!

![sorting-companies](https://user-images.githubusercontent.com/13009507/163827738-61134045-cb66-4101-9337-ccf3961dd770.gif)
